### PR TITLE
Fix error not being shown in error box

### LINKED ISSUE #58: Synchronization error is not included in error box
The error box is empty if there was an error during synchronization.

image

It looks like the problem is that `showErrors` function is only called in `catch` block here, but not in `try` block: https://github.com/swiftype/swiftype-wordpress/blob/69ea1570b18f55052fd19c7019dd0b297c645a09/templates/admin/controls/synchronize.php#L117-L124
I think adding `showErrors(errorMsg);` in `try` block should fix the problem. 
@afoucret Let me know if you agree and if so I could make a PR with the fix.

### PR DESCRIPTION
**Pull request by yakhinvadim**
Closes #58.

This PR adds missing `showError` call in `try` block.

### CODE REVIEW

**Comment by mikeisonthenets** [comment]
Is this a change that can be pushed or is there still an outstanding issue with the checks?

**Comment by yakhinvadim** [comment]
@afoucret I couldn't figure out why CI is failing. Could you take a look, please?

**Comment by yakhinvadim** [comment]
@richkuz with Aurelien unavailable, could someone from the App Search team take a look at this? The issue is preventing customers and support from seeing crawler errors in plugin UI.

**Comment by richkuz** [comment]
@yakhinvadim , I'll take a quick look. @afoucret will return tomorrow, too.

**Comment by richkuz** [comment]
Incremental progress: This [PR](https://github.com/swiftype/swiftype-wordpress/pull/60) fixes the "Install dependencies" step. The tests are still flaky, though.

**Comment by richkuz** [comment]
Annnnd... tests should be passing now with https://github.com/swiftype/swiftype-wordpress/pull/60.

**Comment by yakhinvadim** [comment]
@afoucret please publish a new version 🙏

**Pull request merged**
