### PR TITLE
added an option to search no matter the state of the  object

### PR DESCRIPTION
**Pull request by anthias**

### CODE REVIEW

**Comment by anthias** [comment]
@look can you look this over for me before I tag for release etc.. I did the refactoring we discussed and removed spaces ;)

**Comment by look** [comment]
Nice! I like how that turned out. Assuming it works, seems good to release to me. You'll need to talk to @qhoxie about getting access to push to the WP repository.

Also, don't forget to set up the pre-commit hook.

**Comment by anthias** [comment]
I think I did that right. I setup the pre-commit, but there are no changes in the js, so I don't think it will change anything here right?

@qhoxie can I get push rights to the WP repo? Thanks!

**Comment by look** [comment]
Looks like you bumped the version correctly.

Yeah, if there's no JS changes it won't do anything. I just wanted to make sure you got it set up now so it wouldn't be a surprise later on. :)

**Comment by anthias** [comment]
Sweet. Thanks.

**Comment by look** [comment]
Oh, one other WP plugin tip: If you package this project up as a zip file, you can test the install process in WordPress by uploading the zip file.

IMPORTANT NOTE: If you symlinked the plugin for local development, deleting it so you can re-install deletes your directory! Oops.

Because of that I'd either unsymlink before testing this, or use a different installation (we have an account at WP Engine for testing: mriley.wpengine.com - credentials are in OneLogin.).

**Comment by anthias** [comment]
got it. thanks.

**Pull request merged**
